apiVersion: v1
kind: Service
metadata:
  name: bills-app-service
spec:
  type: NodePort
  selector:
    app: bills-app
  ports:
    - name: bills-user-api
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009

    - name: ticket-generator
      protocol: TCP
      port: 81
      targetPort: 9090
      nodePort: 30008
